### ISSUE TITLE
Choose first-release version number

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Polly.Contrib.MutableBulkheadPolicy#3]
One thing to consider before first publish to nuget: What first version number should we publish under?

The [default starting version number in the template](https://github.com/Polly-Contrib/Polly.Contrib.MutableBulkheadPolicy/blob/init/GitVersionConfig.yaml) is `0.1.0`. However, if we believe the API for this is stable (as looks to be the case), we might go straight to `1.0.0`

Opening this issue so we don't forget.

To set the version number for first publication, set it in `GitVersionConfig.yaml`

@atifield  Thoughts?

**Comment by atifield** [comment]
Thanks, @reisenberger. It makes sense and I also bumped the versions in csproj to v1.0

**Comment by atifield** [comment]
Version updated from the #1
